// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Velocity.Api.Data;

#nullable disable

namespace Velocity.Api.Migrations
{
    [DbContext(typeof(VelocityDbContext))]
    partial class VelocityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Velocity.Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Velocity.Api.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DropoffAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PickupAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CarId", "PickupAt", "DropoffAt");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Velocity.Api.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Badge")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Deposit")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GalleryImageUrls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<int>("HorsePower")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("edaf61bd-00f5-42f7-a086-2c6dde31cf3d"),
                            Brand = "Mercedes-AMG",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 29, 3, 51, 9, 738, DateTimeKind.Unspecified).AddTicks(7868), new TimeSpan(0, 0, 0, 0, 0)),
                            Deposit = 2500m,
                            Description = "Elegantes Coupe mit AMG-Performance, Allrad und komfortabler Langstreckenausstattung.",
                            FuelType = "Benzin",
                            GalleryImageUrls = "",
                            HorsePower = 449,
                            ImageUrl = "/cars/mercedes_cle.png",
                            IsActive = true,
                            IsFeatured = false,
                            Location = "Düsseldorf",
                            MinimumAge = 25,
                            Model = "CLE 53 4MATIC+",
                            PricePerDay = 279m,
                            Seats = 4,
                            Slug = "mercedes-amg-cle-53-4matic",
                            Transmission = "Automatik",
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("48cef016-e349-44a1-9119-8df8cc8e70ec"),
                            Badge = "Beliebt",
                            Brand = "Range Rover",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 29, 3, 51, 9, 739, DateTimeKind.Unspecified).AddTicks(2297), new TimeSpan(0, 0, 0, 0, 0)),
                            Deposit = 2500m,
                            Description = "Luxus-SUV mit souveränem Auftritt, viel Komfort und starker Präsenz.",
                            FuelType = "Benzin",
                            GalleryImageUrls = "",
                            HorsePower = 400,
                            ImageUrl = "/cars/rangerover_velar.png",
                            IsActive = true,
                            IsFeatured = true,
                            Location = "Düsseldorf",
                            MinimumAge = 23,
                            Model = "Velar",
                            PricePerDay = 296m,
                            Seats = 5,
                            Slug = "range-rover-velar",
                            Transmission = "Automatik",
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("9e399b21-8b95-495d-82ed-38d38e7d4ebf"),
                            Brand = "Ferrari",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 29, 3, 51, 9, 739, DateTimeKind.Unspecified).AddTicks(2632), new TimeSpan(0, 0, 0, 0, 0)),
                            Deposit = 10000m,
                            Description = "Hybrid-Supersportwagen mit kompromissloser Ferrari-DNA und extremer Performance.",
                            FuelType = "Hybrid",
                            GalleryImageUrls = "",
                            HorsePower = 1000,
                            ImageUrl = "/cars/ferrari_sf90.png",
                            IsActive = true,
                            IsFeatured = false,
                            Location = "Düsseldorf",
                            MinimumAge = 28,
                            Model = "SF90 Stradale",
                            PricePerDay = 2199m,
                            Seats = 2,
                            Slug = "ferrari-sf90-stradale",
                            Transmission = "Automatik",
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("75cc78c0-dfef-43c0-968b-6dce7fb62d66"),
                            Brand = "Porsche",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 29, 3, 51, 9, 739, DateTimeKind.Unspecified).AddTicks(2639), new TimeSpan(0, 0, 0, 0, 0)),
                            Deposit = 5000m,
                            Description = "Ikonischer Sportwagen mit brachialer Beschleunigung und hoher Alltagstauglichkeit.",
                            FuelType = "Benzin",
                            GalleryImageUrls = "",
                            HorsePower = 650,
                            ImageUrl = "/cars/porsche_turbos.png",
                            IsActive = true,
                            IsFeatured = false,
                            Location = "Düsseldorf",
                            MinimumAge = 25,
                            Model = "911 Turbo S",
                            PricePerDay = 699m,
                            Seats = 4,
                            Slug = "porsche-911-turbo-s",
                            Transmission = "PDK",
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("c17af4c8-bc9c-4b72-a902-d3e603ff3a32"),
                            Brand = "Lamborghini",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 29, 3, 51, 9, 739, DateTimeKind.Unspecified).AddTicks(2643), new TimeSpan(0, 0, 0, 0, 0)),
                            Deposit = 7500m,
                            Description = "Emotionaler V10-Supersportwagen mit maximaler Präsenz und Sound.",
                            FuelType = "Benzin",
                            GalleryImageUrls = "",
                            HorsePower = 640,
                            ImageUrl = "/cars/lamborghini_huracan.png",
                            IsActive = true,
                            IsFeatured = false,
                            Location = "Mülheim",
                            MinimumAge = 28,
                            Model = "Huracán EVO",
                            PricePerDay = 1299m,
                            Seats = 2,
                            Slug = "lamborghini-huracan-evo",
                            Transmission = "Automatik",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("1ec7d313-3fa6-4ad2-9e5e-665316718093"),
                            Brand = "BMW",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 29, 3, 51, 9, 739, DateTimeKind.Unspecified).AddTicks(2647), new TimeSpan(0, 0, 0, 0, 0)),
                            Deposit = 3000m,
                            Description = "Dynamisches M-Coupe mit scharfem Handling und sportlichem Komfort.",
                            FuelType = "Benzin",
                            GalleryImageUrls = "",
                            HorsePower = 510,
                            ImageUrl = "/cars/bmw_m4.png",
                            IsActive = true,
                            IsFeatured = false,
                            Location = "Mülheim",
                            MinimumAge = 23,
                            Model = "M4 Competition",
                            PricePerDay = 349m,
                            Seats = 4,
                            Slug = "bmw-m4-competition",
                            Transmission = "Automatik",
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("9fdeca3b-b9dc-4b15-90f9-5f4e47cb843e"),
                            Brand = "Audi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 29, 3, 51, 9, 739, DateTimeKind.Unspecified).AddTicks(2650), new TimeSpan(0, 0, 0, 0, 0)),
                            Deposit = 4000m,
                            Description = "High-Performance-Kombi mit Raum, Komfort und massiver Leistung.",
                            FuelType = "Benzin",
                            GalleryImageUrls = "",
                            HorsePower = 630,
                            ImageUrl = "/cars/audi_rs6.png",
                            IsActive = true,
                            IsFeatured = false,
                            Location = "Düsseldorf",
                            MinimumAge = 25,
                            Model = "RS6 Performance",
                            PricePerDay = 449m,
                            Seats = 5,
                            Slug = "audi-rs6-performance",
                            Transmission = "Automatik",
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("fbcce759-b8f9-433d-b75d-419024d79d7d"),
                            Brand = "Porsche",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 29, 3, 51, 9, 739, DateTimeKind.Unspecified).AddTicks(2654), new TimeSpan(0, 0, 0, 0, 0)),
                            Deposit = 5000m,
                            Description = "Sportlicher Luxus-SUV mit enormer Leistung und hochwertigem Innenraum.",
                            FuelType = "Benzin",
                            GalleryImageUrls = "",
                            HorsePower = 659,
                            ImageUrl = "/cars/porsche_cayenne.png",
                            IsActive = true,
                            IsFeatured = false,
                            Location = "Mülheim",
                            MinimumAge = 25,
                            Model = "Cayenne Turbo GT",
                            PricePerDay = 649m,
                            Seats = 5,
                            Slug = "porsche-cayenne-turbo-gt",
                            Transmission = "Automatik",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("Velocity.Api.Models.CarBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CarId", "StartAt", "EndAt");

                    b.ToTable("CarBlocks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Velocity.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Velocity.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Velocity.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Velocity.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Velocity.Api.Models.Booking", b =>
                {
                    b.HasOne("Velocity.Api.Models.Car", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Velocity.Api.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Velocity.Api.Models.CarBlock", b =>
                {
                    b.HasOne("Velocity.Api.Models.Car", "Car")
                        .WithMany("Blocks")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Velocity.Api.Models.Car", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
